services:
  db:
    image: postgres:15
    container_name: scheduling_db_prod
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: scheduling_system
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_admin -d scheduling_system"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile-prod
    container_name: scheduling_api_prod
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://user_admin:password123@db:5432/scheduling_system?schema=public"
      JWT_SECRET: "sua_chave_secreta_aqui"
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy

  app:
    build:
      context: ./app
      dockerfile: Dockerfile-prod
    container_name: scheduling_app_prod
    ports:
      - "8081:80"
    depends_on:
      - api

volumes:
  postgres_data_prod: